resources: /nas/depts/006/valdar-lab/users/doreper/resources	

external:
  kallisto: kallisto
  bowtie: bowtie
  #bam.to.emase: /nas/depts/006/valdar-lab/users/doreper/emase/scripts/bam-to-emase
  bam.to.emase: bam-to-emase
  combine.emase.files: combine-emase-files
  run.emase: run-emase
  gbrs: gbrs
  samtools: samtools
  featureCounts: featureCounts    

data:   ../../data
output: /bigfiles/home/doreper/nodrop/output
tmpdir: ../output/tmp
onCluster: no
system.type: mc
mc.cores: 44

mnp:
  mc.cores: 42 #45 #8 #5
  limit: .na
  SSVA.numperm: 100 #400 #20	

  freed: no
  evalprobelimit: .na
  recomputeProbeInfo: no

genome:
  ##folder containing GBRS reference informatio
  GBRS.data: ../../../../../nodrop/data/gbrs75

  ##The transition probability file to be used. AT present, DO, 1gen outbreeding, female
  GBRS.tranprob: tranprob.DO.G1.F.npz


variantdb:
  dbfolder: isvdb-test
  ##num variants allowed
  var_limit: .na
  ##num cc lines allowed
  cc_limit: .na
  chr_range: .na
  # - '16'
  # - '17'
  # - '18'
  # - '19'
  # - 'X'
  # - 'Y'
  # - 'MT'
  # - '1'
  # - '2'
  # - '3'
  # - '4'
  # - '5'
  # - '6'
  # - '7'
  # - '8'
  # - '9'
  # - '10'

  full:
    name: full_1410
    rebuildVCF: yes
    rebuildFounder: yes
    rebuildCC: yes

  exon:
    name: exon_1410
    rebuildVCF: no
    rebuildFounder: yes
    rebuildCC: yes

  imprinted:
    name: imprinted_1410
    rebuildVCF: yes
    rebuildFounder: yes
    rebuildCC: yes
 
ovx:
  numPerm: 1000
  numImp: 500
  iter: 20000
  mc.cores: 1        
  rebuildData: yes
  normalizeBeforeTransform: no
  normalizeAfterTransform: no


