resources: /nas/depts/006/valdar-lab/users/doreper/resources	

saveIntermediates: yes ##yes					

data:   ../data
tmpdir: /netscr/doreper/tmp
onCluster: yes #yes #yes #yes
system.type: killdevil
output: ../output ##../outputfinal

mnp:
  data:   ../data/mnp
  output: ../output/mnp 
  mc.cores: 1 #5
  limit: .na #.na #.na #.na #10 #.na
  SSVA.numperm: 10050 #10050 #.500 #400 #400 ##400 #20

  num.sv: 7 #2
  medianAdjust.p.values: no

  evalprobelimit: .na
  recomputeProbeInfo: no #yes #no

##  ssva.resid: 
  freed: no
  synch: no

crowley:
  ## The type of surrogate variable computation. Options include SSVA, SVA, and SSVA_perm
  surrogat: SSVA	
  num.sv: 1 

  ## Number of probesets which will be modelled, and in which we will test for significance of POE
  limit: 10 #.na ##20  ##.na    ## .na is yaml version of NA

  mc.cores: 1 #3

