onCluster: yes
## system.type: longleaf
## tmpdir: /pine/scr/d/o/doreper/scm_tmpdir
data: ../../data

external:
  kallisto: kallisto
  bowtie: bowtie
  #bam.to.emase: /nas/depts/006/valdar-lab/users/doreper/emase/scripts/bam-to-emase
  bam.to.emase: bam-to-emase
  combine.emase.files: combine-emase-files
  run.emase: run-emase
  gbrs: gbrs
  samtools: samtools
  featureCounts: featureCounts    


experiment:
  ## This is a special case of a data property NOT with resepct to data dir... the seq files are
  ## so big that we store it in a separate folder so that when we sync data with cluster,
  ## we dont end up downloading all the seq files. This only exists on the cluster
  seq.file.root: /nas/depts/006/valdar-lab/users/doreper/nd2016/rnaseq/data
  seq.covariates.file: rnaseq/seq_library/metaseq2.csv 

